basePath: /api/v1
definitions:
  api.CalTestInitResponse:
    properties:
      data:
        properties:
          status_approval:
            type: string
          transaction_id:
            type: string
          warehouse_code:
            type: string
        type: object
      message:
        type: string
    type: object
  api.CreateDraftWarehouseTransferParams:
    properties:
      location_destination:
        type: string
      location_origin:
        type: string
    type: object
  api.DisallocateItemWarehouseTransferParams:
    properties:
      identifier:
        type: string
    type: object
  api.InputItemWarehouseTransferParams:
    properties:
      identifier:
        type: string
    type: object
host: 103.235.75.94:8000
info:
  contact:
    email: archer.lukman@gmail.com
    name: API Support
  description: This is my service API documentation for scm-simple.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: scm-simple API
  version: "1.0"
paths:
  /api/v1/warehouse/create-draft-transfer:
    post:
      consumes:
      - application/json
      description: Create New Draft Transaction Warehouse to Warehouse
      parameters:
      - description: draft transaction transfer payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.CreateDraftWarehouseTransferParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create New Draft Transaction
      tags:
      - warehouse_service item_transfer
  /api/v1/warehouse/disallocate-item/:transaction_number:
    post:
      consumes:
      - application/json
      description: User scan identifier for each item that will be takenout as set
        to be
      parameters:
      - description: item transfer payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.DisallocateItemWarehouseTransferParams'
      - description: transaction number identifier
        in: path
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Takeout each item one by one(serial_number) in Transaction
      tags:
      - warehouse_service item_transfer
  /api/v1/warehouse/input-item/:transaction_number:
    post:
      consumes:
      - application/json
      description: User scan identifier for each item that will be delivered as ALLOCATED
      parameters:
      - description: item transfer payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.InputItemWarehouseTransferParams'
      - description: transaction number identifier
        in: path
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Input each item one by one(serial_number) in Transaction
      tags:
      - warehouse_service item_transfer
  /api/v1/warehouse/set-status/:transaction_number/:status:
    put:
      consumes:
      - application/json
      description: Authorized User can update transaction process ("submit", "reject",
        "cancel", "approve")
      parameters:
      - description: transaction number identifier
        in: path
        name: request
        required: true
        type: string
      - description: status to update
        in: path
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
      summary: set update status Transaction
      tags:
      - warehouse_service item_transfer
  /api/warehouse/:location_code:
    get:
      consumes:
      - application/json
      description: Search location by location code, customer, technician, warehouse
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      - description: Location code
        in: path
        name: location_code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Search location by location code
      tags:
      - location warehouse customer technician
  /test-init/{transaction_id}:
    get:
      consumes:
      - application/json
      description: Call Test Init after construct code for swagger init
      parameters:
      - description: Transaction Id
        in: path
        name: transaction_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CalTestInitResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Test init for swagger docs
      tags:
      - callany
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
